# https://docs.github.com/en/actions/learn-github-actions/contexts

---
name: Gittyup
on:
  push:
    branches:
      - master
  pull_request:
  page_build:
  workflow_dispatch:

env:
  IS_RELEASE: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/gittyup_v') }}

jobs:
  appimage:
    name: AppImage
    runs-on: ubuntu-20.04

    container:
      image: ubuntu:xenial

    steps:
      - name: Install prerequisites
        run: |
          apt-get -y update
          apt-get -y install git sudo
      - uses: actions/checkout@v3
      - name: Build AppImage
        run: |
          bash -ex appimage-builder/build.sh
      - name: Create release and upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage /home/runner/work/Gittyup/Gittyup/build/release/Gittyup-*.AppImage
